robot_cfg:
  kinematics:
    add_object_link: false
    asset_root_path: /media/eencku/2TBDATA/yusian-ubuntu/UR5_curobo/assets/robot/ur_description
    base_link: base_link
    collision_link_names: [shoulder_link, upper_arm_link, forearm_link, wrist_1_link,
      wrist_2_link, wrist_3_link, tool0, robotiq_arg2f_base_link, left_outer_knuckle,
      left_outer_finger, left_inner_finger, left_inner_knuckle, right_outer_knuckle,
      right_outer_finger, right_inner_finger, right_inner_knuckle, camera_mount, ft300_coupling,
      wrist_camera]
    collision_sphere_buffer: 0.0
    collision_spheres:
      shoulder_link:
      - center: [0.0, 0.0, 0.0]
        radius: 0.1
      upper_arm_link:
      - center: [-0.416, -0.0, 0.143]
        radius: 0.078
      - center: [-0.015, 0.0, 0.134]
        radius: 0.077
      - center: [-0.14, 0.0, 0.138]
        radius: 0.062
      - center: [-0.285, -0.001, 0.139]
        radius: 0.061
      - center: [-0.376, 0.001, 0.138]
        radius: 0.077
      - center: [-0.222, 0.001, 0.139]
        radius: 0.061
      - center: [-0.055, 0.008, 0.14]
        radius: 0.07
      - center: [-0.001, -0.002, 0.143]
        radius: 0.08
      forearm_link:
      - center: [-0.01, 0.002, 0.031]
        radius: 0.072
      - center: [-0.387, 0.0, 0.014]
        radius: 0.057
      - center: [-0.121, -0.0, 0.006]
        radius: 0.057
      - center: [-0.206, 0.001, 0.007]
        radius: 0.057
      - center: [-0.312, -0.001, 0.006]
        radius: 0.056
      - center: [-0.057, 0.003, 0.008]
        radius: 0.065
      - center: [-0.266, 0.0, 0.006]
        radius: 0.057
      - center: [-0.397, -0.001, -0.018]
        radius: 0.052
      - center: [-0.164, -0.0, 0.007]
        radius: 0.057
      wrist_1_link:
      - center: [-0.0, 0.0, -0.009]
        radius: 0.047
      - center: [-0.0, 0.0, -0.052]
        radius: 0.047
      - center: [-0.002, 0.027, -0.001]
        radius: 0.045
      - center: [0.001, -0.01, 0.0]
        radius: 0.046
      wrist_2_link:
      - center: [0.0, -0.01, -0.001]
        radius: 0.047
      - center: [0.0, 0.008, -0.001]
        radius: 0.047
      - center: [0.001, -0.001, -0.036]
        radius: 0.047
      - center: [0.001, -0.03, -0.0]
        radius: 0.047
      wrist_3_link:
      - center: [0.001, 0.001, -0.029]
        radius: 0.043
      tool0:
      - center: [0.001, 0.001, 0.05]
        radius: -0.01
      robotiq_arg2f_base_link:
      - center: [-0.0006354808574542403, 0.0019891983829438686, 0.03540361672639847]
        radius: 0.048546627163887024
      - center: [0.006852868478745222, 0.015351505018770695, 0.08293740451335907]
        radius: 0.0063859871588647366
      - center: [-0.0015789091121405363, -0.00609505595639348, 0.07478470355272293]
        radius: 0.019140908494591713
      left_outer_knuckle:
      - center: [0.0004971438320353627, 0.025133393704891205, 0.0005888671148568392]
        radius: 0.013210617005825043
      - center: [-0.0008109845221042633, 0.0029730487149208784, -0.0012351118493825197]
        radius: 0.01317368634045124
      left_outer_finger:
      - center: [0.00017095330986194313, 0.005270019639283419, 0.03780512511730194]
        radius: 0.017207371070981026
      - center: [-0.00014996284153312445, 0.00039011603803373873, 0.0055664051324129105]
        radius: 0.01586551032960415
      - center: [0.008289630524814129, 0.000571255455724895, 0.024478605017066002]
        radius: 0.006606700364500284
      left_inner_finger:
      - center: [0.00020053527259733528, -0.0016857165610417724, 0.0009121943148784339]
        radius: 0.009219949133694172
      - center: [-0.0005387325654737651, -0.017562782391905785, 0.009723472408950329]
        radius: 0.012506476603448391
      - center: [-0.00024800392566248775, -0.01574450358748436, 0.0327567383646965]
        radius: 0.011503025889396667
      left_inner_knuckle:
      - center: [0.019257526844739914, -0.004620068706572056, 0.003819508710876107]
        radius: 0.0020000000949949026
      - center: [-0.012000000104308128, 0.04095232114195824, 0.041708510369062424]
        radius: 0.0020000000949949026
      - center: [0.007553253322839737, 0.02794777788221836, 0.04196125641465187]
        radius: 0.0020000000949949026
      - center: [-0.012000000104308128, 0.007611594628542662, 0.0030095521360635757]
        radius: 0.0020000000949949026
      - center: [0.013840684667229652, 0.012895147316157818, 0.014361763373017311]
        radius: 0.0020000000949949026
      right_outer_knuckle:
      - center: [-0.001530019799247384, 0.02485998533666134, 0.004760806914418936]
        radius: 0.013748837634921074
      - center: [-0.0011614676332101226, 0.001717766746878624, 4.439771510078572e-05]
        radius: 0.011118831112980843
      right_outer_finger:
      - center: [0.001141592743806541, -0.0003103759081568569, 0.008690834045410156]
        radius: 0.018282277509570122
      - center: [-0.0022315785754472017, 0.005166018381714821, 0.03881010040640831]
        radius: 0.017344096675515175
      right_inner_finger:
      - center: [0.00012799003161489964, -0.0017160945571959019, -0.0002104769228026271]
        radius: 0.009107347577810287
      - center: [0.00040427246131002903, -0.01742568612098694, 0.009905394166707993]
        radius: 0.01309297326952219
      - center: [0.0012071619275957346, -0.015827763825654984, 0.03501654043793678]
        radius: 0.010859389789402485
      right_inner_knuckle:
      - center: [0.014652767218649387, 0.009794546291232109, 0.020706553012132645]
        radius: 0.0020000000949949026
      - center: [0.012000000104308128, -0.004896597471088171, -0.002347733126953244]
        radius: 0.0020000000949949026
      - center: [-0.012000000104308128, -0.0019974629394710064, 0.006084308959543705]
        radius: 0.0020000000949949026
      - center: [-0.009923421777784824, 0.025069529190659523, 0.020114028826355934]
        radius: 0.0020000000949949026
      - center: [0.012000000104308128, 0.042721185833215714, 0.04267319291830063]
        radius: 0.0020000000949949026
      - center: [-0.012000000104308128, 0.04019271582365036, 0.04031769931316376]
        radius: 0.0020000000949949026
      - center: [0.007481858134269714, 0.025102805346250534, 0.034072890877723694]
        radius: 0.0020000000949949026
      camera_mount:
      - center: [0.0, -0.03, 0.0]
        radius: 0.018
      - center: [0.0, 0.0, 0.0]
        radius: 0.018
      - center: [0.0, 0.03, 0.0]
        radius: 0.018
      ft300_coupling:
      - center: [-0.021, -0.021, 0.008]
        radius: 0.024
      - center: [-0.021, 0.021, 0.008]
        radius: 0.024
      - center: [0.021, -0.021, 0.008]
        radius: 0.024
      - center: [0.021, 0.021, 0.008]
        radius: 0.024
      - center: [-0.021, -0.021, 0.024]
        radius: 0.024
      - center: [-0.021, 0.021, 0.024]
        radius: 0.024
      - center: [0.021, -0.021, 0.024]
        radius: 0.024
      - center: [0.021, 0.021, 0.024]
        radius: 0.024
      - center: [-0.021, -0.021, 0.038]
        radius: 0.024
      - center: [-0.021, 0.021, 0.038]
        radius: 0.024
      - center: [0.021, -0.021, 0.038]
        radius: 0.024
      - center: [0.021, 0.021, 0.038]
        radius: 0.024
      wrist_camera:
      - center: [-0.021, -0.015, 0.0]
        radius: 0.023
      - center: [-0.021, 0.015, 0.0]
        radius: 0.023
      - center: [0.0, -0.015, 0.0]
        radius: 0.023
      - center: [0.0, 0.015, 0.0]
        radius: 0.023
      - center: [0.021, -0.015, 0.0]
        radius: 0.023
      - center: [0.021, 0.015, 0.0]
        radius: 0.023
    cspace:
      acceleration_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.5, 1.5, 1.5]
      default_joint_position: [0.0, -2.2, 1.9, -1.383, -1.57, 0.0]
      jerk_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint,
        wrist_2_joint, wrist_3_joint]
      max_acceleration: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
      max_jerk: [500.0, 500.0, 500.0, 500.0, 500.0, 500.0]
      null_space_maximum_distance: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      position_limit_clip: 0.0
      velocity_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    debug: null
    external_asset_path: null
    external_robot_configs_path: null
    extra_collision_spheres: null
    extra_links: {}
    format_version: 2.0
    grasp_contact_link_names: null
    load_meshes: false
    load_tool_frames_with_mesh: false
    lock_joints: {left_outer_knuckle_joint: 0.0, right_outer_knuckle_joint: 0.0, left_inner_knuckle_joint: 0.0,
      right_inner_knuckle_joint: 0.0, left_inner_finger_joint: -0.0, right_inner_finger_joint: -0.0}
    mesh_link_names: [base_link_inertia, shoulder_link, upper_arm_link, forearm_link,
      wrist_1_link, wrist_2_link, wrist_3_link, robotiq_arg2f_base_link, left_outer_knuckle,
      left_outer_finger, left_inner_finger, left_inner_finger_pad, left_inner_knuckle,
      right_outer_knuckle, right_outer_finger, right_inner_finger, right_inner_finger_pad,
      right_inner_knuckle, ft300_coupling, ft300_sensor, wrist_camera, camera_mount]
    self_collision_buffer: {base_link_inertia: 0.0, camera_mount: 0.0, forearm_link: 0,
      ft300_coupling: 0.0, ft300_sensor: 0.0, left_inner_finger: 0.0, left_inner_finger_pad: 0.0,
      left_inner_knuckle: 0.0, left_outer_finger: 0.0, left_outer_knuckle: 0.0, right_inner_finger: 0.0,
      right_inner_finger_pad: 0.0, right_inner_knuckle: 0.0, right_outer_finger: 0.0,
      right_outer_knuckle: 0.0, robotiq_arg2f_base_link: 0.0, shoulder_link: 0.0,
      upper_arm_link: 0, wrist_1_link: 0, wrist_2_link: 0, wrist_3_link: 0, wrist_camera: 0.0,
      tool0: 0.025}
    self_collision_ignore:
      base: [base_link]
      base_link: [base_link_inertia, base]
      base_link_inertia: [base_link, shoulder_link]
      camera_link: [camera_mount]
      camera_mount: [camera_link, ft300_sensor, left_inner_finger, left_inner_knuckle,
        left_outer_finger, left_outer_knuckle, right_inner_finger, right_inner_knuckle,
        right_outer_finger, right_outer_knuckle, robotiq_arg2f_base_link, tool0, wrist_3_link,
        wrist_camera]
      flange: [wrist_3_link, tool0]
      forearm_link: [upper_arm_link, wrist_1_link, wrist_2_link, wrist_3_link]
      ft300_coupling: [camera_mount, ft300_sensor, tool0, wrist_3_link, wrist_camera]
      ft300_sensor: [camera_mount, ft300_coupling, robotiq_arg2f_base_link, tool0,
        wrist_3_link, wrist_camera]
      grasp_frame: [robotiq_arg2f_base_link]
      left_inner_finger: [left_outer_finger, left_inner_finger_pad, left_inner_knuckle,
        right_inner_finger_pad, camera_mount, right_outer_knuckle, ft300_coupling,
        ft300_sensor, wrist_camera]
      left_inner_finger_pad: [left_inner_finger, left_inner_knuckle, right_inner_finger,
        right_inner_finger_pad, camera_mount, ft300_coupling, ft300_sensor, wrist_camera]
      left_inner_knuckle: [robotiq_arg2f_base_link, camera_mount, right_outer_knuckle,
        right_outer_finger, ft300_coupling, ft300_sensor, wrist_camera]
      left_outer_finger: [left_outer_knuckle, left_inner_finger, camera_mount, right_outer_knuckle,
        right_outer_finger, right_inner_knuckle, ft300_coupling, ft300_sensor, wrist_camera]
      left_outer_knuckle: [robotiq_arg2f_base_link, left_outer_finger, camera_mount,
        left_inner_finger, left_inner_finger_pad, left_inner_knuckle, right_outer_knuckle,
        right_outer_finger, right_inner_finger, right_inner_finger_pad, right_inner_knuckle,
        ft300_coupling, ft300_sensor, wrist_camera]
      right_inner_finger: [right_outer_finger, right_inner_finger_pad, right_inner_knuckle,
        camera_mount, ft300_coupling, ft300_sensor, wrist_camera]
      right_inner_finger_pad: [right_inner_finger, right_inner_knuckle, camera_mount,
        ft300_coupling, ft300_sensor, wrist_camera]
      right_inner_knuckle: [robotiq_arg2f_base_link, camera_mount, ft300_coupling,
        ft300_sensor, wrist_camera]
      right_outer_finger: [right_outer_knuckle, right_inner_finger, camera_mount,
        ft300_coupling, ft300_sensor, wrist_camera]
      right_outer_knuckle: [robotiq_arg2f_base_link, right_outer_finger, camera_mount,
        right_inner_finger, right_inner_finger_pad, ft300_coupling, ft300_sensor,
        wrist_camera]
      robotiq_arg2f_base_link: [tool0, left_outer_knuckle, left_inner_knuckle, right_outer_knuckle,
        right_inner_knuckle, grasp_frame, camera_mount, right_outer_finger, ft300_sensor,
        wrist_camera, left_outer_finger, ft300_coupling]
      shoulder_link: [base_link_inertia, tool0, upper_arm_link]
      tool0: [flange, robotiq_arg2f_base_link, ft300_coupling, wrist_camera]
      upper_arm_link: [forearm_link, shoulder_link, tool0]
      wrist_1_link: [camera_mount, forearm_link, ft300_coupling, ft300_sensor, left_inner_finger,
        left_inner_finger_pad, left_inner_knuckle, left_outer_finger, left_outer_knuckle,
        right_inner_finger, right_inner_finger_pad, right_inner_knuckle, right_outer_finger,
        right_outer_knuckle, robotiq_arg2f_base_link, tool0, wrist_2_link, wrist_3_link,
        wrist_camera]
      wrist_2_link: [camera_mount, ft300_coupling, ft300_sensor, left_inner_finger,
        left_inner_finger_pad, left_inner_knuckle, left_outer_finger, left_outer_knuckle,
        right_inner_finger, right_inner_finger_pad, right_inner_knuckle, right_outer_finger,
        right_outer_knuckle, robotiq_arg2f_base_link, tool0, wrist_1_link, wrist_3_link,
        wrist_camera]
      wrist_3_link: [camera_mount, flange, ft300_coupling, ft300_sensor, left_inner_finger,
        left_inner_finger_pad, left_inner_knuckle, left_outer_finger, left_outer_knuckle,
        right_inner_finger, right_inner_finger_pad, right_inner_knuckle, right_outer_finger,
        right_outer_knuckle, robotiq_arg2f_base_link, tool0, wrist_2_link, wrist_camera]
      wrist_camera: [camera_mount, ft300_coupling, ft300_sensor, left_inner_knuckle,
        left_outer_knuckle, right_inner_knuckle, right_outer_knuckle, robotiq_arg2f_base_link,
        tool0]
    tool_frames: [grasp_frame, camera_link]
    urdf_path: /media/eencku/2TBDATA/yusian-ubuntu/UR5_curobo/assets/robot/ur_description/ur5e_robotiq_2f_85.urdf
    use_external_assets: false
    use_global_cumul: true
