robot_cfg:
  kinematics:
    add_object_link: false
    asset_root_path: /media/eencku/2TBDATA/yusian-ubuntu/UR5_curobo/assets/robot/ur_description
    base_link: base_link
    collision_link_names: [shoulder_link, upper_arm_link, forearm_link, wrist_1_link,
      wrist_2_link, wrist_3_link, tool0, robotiq_arg2f_base_link, left_outer_knuckle,
      left_outer_finger, left_inner_finger, left_inner_knuckle, right_outer_knuckle,
      right_outer_finger, right_inner_finger, right_inner_knuckle, camera_mount, ft300_coupling,
      wrist_camera]
    collision_sphere_buffer: 0.0
    collision_spheres:
      shoulder_link:
      - center: [0.0, 0.0, 0.0]
        radius: 0.1
      upper_arm_link:
      - center: [-0.416, -0.0, 0.143]
        radius: 0.078
      - center: [-0.015, 0.0, 0.134]
        radius: 0.077
      - center: [-0.14, 0.0, 0.138]
        radius: 0.062
      - center: [-0.285, -0.001, 0.139]
        radius: 0.061
      - center: [-0.376, 0.001, 0.138]
        radius: 0.077
      - center: [-0.222, 0.001, 0.139]
        radius: 0.061
      - center: [-0.055, 0.008, 0.14]
        radius: 0.07
      - center: [-0.001, -0.002, 0.143]
        radius: 0.08
      forearm_link:
      - center: [-0.01, 0.002, 0.031]
        radius: 0.072
      - center: [-0.387, 0.0, 0.014]
        radius: 0.057
      - center: [-0.121, -0.0, 0.006]
        radius: 0.057
      - center: [-0.206, 0.001, 0.007]
        radius: 0.057
      - center: [-0.312, -0.001, 0.006]
        radius: 0.056
      - center: [-0.057, 0.003, 0.008]
        radius: 0.065
      - center: [-0.266, 0.0, 0.006]
        radius: 0.057
      - center: [-0.397, -0.001, -0.018]
        radius: 0.052
      - center: [-0.164, -0.0, 0.007]
        radius: 0.057
      wrist_1_link:
      - center: [-0.0, 0.0, -0.009]
        radius: 0.047
      - center: [-0.0, 0.0, -0.052]
        radius: 0.047
      - center: [-0.002, 0.027, -0.001]
        radius: 0.045
      - center: [0.001, -0.01, 0.0]
        radius: 0.046
      wrist_2_link:
      - center: [0.0, -0.01, -0.001]
        radius: 0.047
      - center: [0.0, 0.008, -0.001]
        radius: 0.047
      - center: [0.001, -0.001, -0.036]
        radius: 0.047
      - center: [0.001, -0.03, -0.0]
        radius: 0.047
      wrist_3_link:
      - center: [0.001, 0.001, -0.029]
        radius: 0.043
      tool0:
      - center: [0.001, 0.001, 0.05]
        radius: -0.01
      robotiq_arg2f_base_link:
      - center: [-0.0005425337003543973, -0.0007462625508196652, 0.03263619542121887]
        radius: 0.046756234019994736
      - center: [0.0013862187042832375, 0.013752930797636509, 0.07552504539489746]
        radius: 0.017153747379779816
      - center: [0.0007300973520614207, -0.011343526653945446, 0.07551786303520203]
        radius: 0.016400514170527458
      left_outer_knuckle:
      - center: [0.0007065957179293036, 0.0271291546523571, 0.003408880904316902]
        radius: 0.014154292643070221
      - center: [1.7767404642654583e-05, 0.0028232361655682325, 0.0001558218791615218]
        radius: 0.010775730945169926
      left_outer_finger:
      - center: [-0.00012602529022842646, 0.004907440394163132, 0.009184932336211205]
        radius: 0.016677439212799072
      - center: [-0.0017875824123620987, 0.001683832728303969, 0.037779759615659714]
        radius: 0.016689857468008995
      - center: [0.009674004279077053, 0.0004750624066218734, 0.019703498110175133]
        radius: 0.003554157679900527
      left_inner_finger:
      - center: [-0.00036850504693575203, -0.0023841415531933308, 0.0007310482324101031]
        radius: 0.009189963340759277
      - center: [-0.0004849464166909456, -0.015525586903095245, 0.011005639098584652]
        radius: 0.012866725213825703
      - center: [-0.0007541743689216673, -0.015717370435595512, 0.034930385649204254]
        radius: 0.009656764566898346
      left_inner_knuckle:
      - center: [-0.018382035195827484, 0.002563981106504798, -0.005414763931185007]
        radius: 0.0020000000949949026
      - center: [-0.013500000350177288, 0.0388730987906456, 0.04186743497848511]
        radius: 0.0020000000949949026
      - center: [-0.014248549938201904, 0.0052799503318965435, 0.0154206408187747]
        radius: 0.0020000000949949026
      - center: [0.018681876361370087, 0.005604943260550499, 0.008268898352980614]
        radius: 0.0020000000949949026
      - center: [0.017000000923871994, 0.017931170761585236, 0.027999667450785637]
        radius: 0.0020000000949949026
      right_outer_knuckle:
      - center: [-0.0020481019746512175, 0.025235619395971298, 0.0016369601944461465]
        radius: 0.013432598672807217
      - center: [-0.00010367659706389531, 0.0013814757112413645, -0.000680865254253149]
        radius: 0.010730912908911705
      right_outer_finger:
      - center: [-0.0002856834325939417, 0.0007582781254313886, 0.008431963622570038]
        radius: 0.016025837510824203
      - center: [-0.0026960070244967937, 0.004528381396085024, 0.03567451611161232]
        radius: 0.018272021785378456
      - center: [-0.010919780470430851, 0.007743042893707752, 0.052503347396850586]
        radius: 0.001560661825351417
      - center: [-0.010636567138135433, 0.004254174884408712, 0.04010273143649101]
        radius: 0.002887439215555787
      right_inner_finger:
      - center: [0.000181665614945814, -0.0022041206248104572, 0.00019874656572937965]
        radius: 0.00911211222410202
      - center: [-0.0009928055806085467, -0.016717836260795593, 0.010192151181399822]
        radius: 0.011823196895420551
      - center: [-0.0005840255180373788, -0.01461096666753292, 0.03323984891176224]
        radius: 0.01108541153371334
      right_inner_knuckle:
      - center: [0.00012267479905858636, 0.02526525780558586, 0.020504210144281387]
        radius: 0.0020000000949949026
      - center: [-0.015023643150925636, -0.0034437563735991716, 0.0052064936608076096]
        radius: 0.0020000000949949026
      - center: [0.007499999832361937, 0.035464342683553696, 0.03979337960481644]
        radius: 0.0020000000949949026
      - center: [-0.013500000350177288, 0.035162437707185745, 0.04196269437670708]
        radius: 0.0020000000949949026
      - center: [-0.015266096219420433, 0.013260634616017342, 0.02476482279598713]
        radius: 0.0020000000949949026
      - center: [0.012000000104308128, -0.002885401714593172, 0.003493210067972541]
        radius: 0.0020000000949949026
      camera_mount:
      - center: [0.0, -0.03, 0.0]
        radius: 0.018
      - center: [0.0, 0.0, 0.0]
        radius: 0.018
      - center: [0.0, 0.03, 0.0]
        radius: 0.018
      ft300_coupling:
      - center: [-0.021, -0.021, 0.008]
        radius: 0.024
      - center: [-0.021, 0.021, 0.008]
        radius: 0.024
      - center: [0.021, -0.021, 0.008]
        radius: 0.024
      - center: [0.021, 0.021, 0.008]
        radius: 0.024
      - center: [-0.021, -0.021, 0.024]
        radius: 0.024
      - center: [-0.021, 0.021, 0.024]
        radius: 0.024
      - center: [0.021, -0.021, 0.024]
        radius: 0.024
      - center: [0.021, 0.021, 0.024]
        radius: 0.024
      - center: [-0.021, -0.021, 0.038]
        radius: 0.024
      - center: [-0.021, 0.021, 0.038]
        radius: 0.024
      - center: [0.021, -0.021, 0.038]
        radius: 0.024
      - center: [0.021, 0.021, 0.038]
        radius: 0.024
      wrist_camera:
      - center: [-0.021, -0.015, 0.0]
        radius: 0.023
      - center: [-0.021, 0.015, 0.0]
        radius: 0.023
      - center: [0.0, -0.015, 0.0]
        radius: 0.023
      - center: [0.0, 0.015, 0.0]
        radius: 0.023
      - center: [0.021, -0.015, 0.0]
        radius: 0.023
      - center: [0.021, 0.015, 0.0]
        radius: 0.023
    cspace:
      acceleration_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.5, 1.5, 1.5]
      default_joint_position: [0.0, -2.2, 1.9, -1.383, -1.57, 0.0]
      jerk_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      joint_names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint,
        wrist_2_joint, wrist_3_joint]
      max_acceleration: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
      max_jerk: [500.0, 500.0, 500.0, 500.0, 500.0, 500.0]
      null_space_maximum_distance: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      position_limit_clip: 0.0
      velocity_scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    debug: null
    external_asset_path: null
    external_robot_configs_path: null
    extra_collision_spheres: null
    extra_links: {}
    format_version: 2.0
    grasp_contact_link_names: null
    load_meshes: false
    load_tool_frames_with_mesh: false
    lock_joints: {left_outer_knuckle_joint: 0.0}
    mesh_link_names: [base_link_inertia, shoulder_link, upper_arm_link, forearm_link,
      wrist_1_link, wrist_2_link, wrist_3_link, robotiq_arg2f_base_link, left_outer_knuckle,
      left_outer_finger, left_inner_finger, left_inner_finger_pad, left_inner_knuckle,
      right_outer_knuckle, right_outer_finger, right_inner_finger, right_inner_finger_pad,
      right_inner_knuckle, ft300_coupling, ft300_sensor, wrist_camera, camera_mount]
    self_collision_buffer: {base_link_inertia: 0.0, camera_mount: 0.0, forearm_link: 0,
      ft300_coupling: 0.0, ft300_sensor: 0.0, left_inner_finger: 0.0, left_inner_finger_pad: 0.0,
      left_inner_knuckle: 0.0, left_outer_finger: 0.0, left_outer_knuckle: 0.0, right_inner_finger: 0.0,
      right_inner_finger_pad: 0.0, right_inner_knuckle: 0.0, right_outer_finger: 0.0,
      right_outer_knuckle: 0.0, robotiq_arg2f_base_link: 0.0, shoulder_link: 0.0,
      upper_arm_link: 0, wrist_1_link: 0, wrist_2_link: 0, wrist_3_link: 0, wrist_camera: 0.0,
      tool0: 0.025}
    self_collision_ignore:
      base: [base_link]
      base_link: [base_link_inertia, base]
      base_link_inertia: [base_link, shoulder_link]
      camera_link: [camera_mount]
      camera_mount: [camera_link, ft300_sensor, left_inner_finger, left_inner_knuckle,
        left_outer_finger, left_outer_knuckle, right_inner_finger, right_inner_knuckle,
        right_outer_finger, right_outer_knuckle, robotiq_arg2f_base_link, tool0, wrist_3_link,
        wrist_camera]
      flange: [wrist_3_link, tool0]
      forearm_link: [upper_arm_link, wrist_1_link, wrist_2_link, wrist_3_link]
      ft300_coupling: [camera_mount, ft300_sensor, tool0, wrist_3_link, wrist_camera]
      ft300_sensor: [camera_mount, ft300_coupling, robotiq_arg2f_base_link, tool0,
        wrist_3_link, wrist_camera]
      grasp_frame: [robotiq_arg2f_base_link]
      left_inner_finger: [left_outer_finger, left_inner_finger_pad, left_inner_knuckle,
        camera_mount, right_outer_knuckle, right_outer_finger, ft300_coupling, ft300_sensor,
        wrist_camera]
      left_inner_finger_pad: [left_inner_finger, camera_mount, left_inner_knuckle,
        right_outer_knuckle, right_outer_finger, right_inner_knuckle, ft300_coupling,
        ft300_sensor, wrist_camera]
      left_inner_knuckle: [robotiq_arg2f_base_link, camera_mount, right_outer_knuckle,
        right_outer_finger, right_inner_finger, right_inner_finger_pad, right_inner_knuckle,
        ft300_coupling, ft300_sensor, wrist_camera]
      left_outer_finger: [left_outer_knuckle, left_inner_finger, camera_mount, left_inner_finger_pad,
        left_inner_knuckle, right_outer_knuckle, right_outer_finger, right_inner_finger,
        right_inner_finger_pad, right_inner_knuckle, ft300_coupling, ft300_sensor,
        wrist_camera]
      left_outer_knuckle: [robotiq_arg2f_base_link, left_outer_finger, camera_mount,
        left_inner_finger, left_inner_finger_pad, left_inner_knuckle, right_outer_knuckle,
        right_outer_finger, right_inner_finger, right_inner_finger_pad, right_inner_knuckle,
        ft300_coupling, ft300_sensor, wrist_camera]
      right_inner_finger: [right_outer_finger, right_inner_finger_pad, right_inner_knuckle,
        camera_mount, ft300_coupling, ft300_sensor, wrist_camera]
      right_inner_finger_pad: [right_inner_finger, camera_mount, right_inner_knuckle,
        ft300_coupling, ft300_sensor, wrist_camera]
      right_inner_knuckle: [robotiq_arg2f_base_link, camera_mount, ft300_coupling,
        ft300_sensor, wrist_camera]
      right_outer_finger: [right_outer_knuckle, right_inner_finger, camera_mount,
        right_inner_finger_pad, ft300_coupling, ft300_sensor, wrist_camera]
      right_outer_knuckle: [robotiq_arg2f_base_link, right_outer_finger, camera_mount,
        right_inner_finger, right_inner_finger_pad, right_inner_knuckle, ft300_coupling,
        ft300_sensor, wrist_camera]
      robotiq_arg2f_base_link: [tool0, left_outer_knuckle, left_inner_knuckle, right_outer_knuckle,
        right_inner_knuckle, grasp_frame, camera_mount, ft300_sensor, wrist_camera,
        left_inner_finger, left_inner_finger_pad, right_inner_finger, right_inner_finger_pad,
        ft300_coupling]
      shoulder_link: [base_link_inertia, tool0, upper_arm_link]
      tool0: [flange, robotiq_arg2f_base_link, ft300_coupling, wrist_camera]
      upper_arm_link: [forearm_link, shoulder_link, tool0]
      wrist_1_link: [camera_mount, forearm_link, ft300_coupling, ft300_sensor, left_inner_finger,
        left_inner_finger_pad, left_inner_knuckle, left_outer_finger, left_outer_knuckle,
        right_inner_finger, right_inner_finger_pad, right_inner_knuckle, right_outer_finger,
        right_outer_knuckle, robotiq_arg2f_base_link, tool0, wrist_2_link, wrist_3_link,
        wrist_camera]
      wrist_2_link: [camera_mount, ft300_coupling, ft300_sensor, left_inner_finger,
        left_inner_finger_pad, left_inner_knuckle, left_outer_finger, left_outer_knuckle,
        right_inner_finger, right_inner_finger_pad, right_inner_knuckle, right_outer_finger,
        right_outer_knuckle, robotiq_arg2f_base_link, tool0, wrist_1_link, wrist_3_link,
        wrist_camera]
      wrist_3_link: [camera_mount, flange, ft300_coupling, ft300_sensor, left_inner_finger,
        left_inner_finger_pad, left_inner_knuckle, left_outer_finger, left_outer_knuckle,
        right_inner_finger, right_inner_finger_pad, right_inner_knuckle, right_outer_finger,
        right_outer_knuckle, robotiq_arg2f_base_link, tool0, wrist_2_link, wrist_camera]
      wrist_camera: [camera_mount, ft300_coupling, ft300_sensor, left_inner_knuckle,
        left_outer_knuckle, right_inner_knuckle, right_outer_knuckle, robotiq_arg2f_base_link,
        tool0]
    tool_frames: [grasp_frame, camera_link]
    urdf_path: /media/eencku/2TBDATA/yusian-ubuntu/UR5_curobo/assets/robot/ur_description/ur5e_robotiq_2f_85.urdf
    use_external_assets: false
    use_global_cumul: true
